/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205236;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainWindowTest {
    @Test //**内容　あいこの時にジャンケンが続く*/
    void selectHandTest(){
        int inputHand = 0;
        int computHand = 0;

        assertEquals(0, inputHand);
        assertEquals(0, computHand);
    }
}